overrides:
  form-data@<2.5.4: '>=2.5.4'
  jpeg-js@<0.4.0: '>=0.4.0'
  jpeg-js@<0.4.4: '>=0.4.4'
  minimist@<0.2.1: '>=0.2.1'
  minimist@<0.2.4: '>=0.2.4'
  qs@<6.14.1: '>=6.14.1'
  tough-cookie@<4.1.3: '>=4.1.3'
